# Generated by Django 4.2.1 on 2023-07-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedwrestler',
            name='add_information',
            field=models.TextField(null=True),
        ),
    ]
