# Generated by Django 4.2.1 on 2023-09-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_scrapedwrestler_add_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_set', models.TextField()),
            ],
        ),
    ]
