# Generated by Django 4.0.2 on 2023-04-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_username', models.CharField(max_length=50)),
                ('to_username', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
