# Generated by Django 4.2.1 on 2023-08-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_messaging_mail_to_register_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_username', models.CharField(max_length=50)),
                ('to_username', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
