# Generated by Django 4.2.1 on 2023-08-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_privatemessaging_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessaging',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
